baseurl = "/"
title = "Simply Theme Demo"
languageCode = "en-us"
theme = "simply"
author = "Akhlis"
paginate = "6" # Number of posts per page
copyright = "&copy; 2017. All rights reserved."
disqusShortname = "calina-ghost" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id


[Author]
    name = "John Doe"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "images/author.jpg"
    
[Params]
    subtitle = "Just another site" # Subtitle of your site
    description = " John Doe's Personal blog about everything" # Description of your site
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]
    
# Navbar menu to be shown on the left-hand side of the navigation bar

[[menu.navbar]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.navbar]]
    url = "/post/"
    name = "About"
    weight = 2

[[menu.navbar]]
    url = "/project/"
    name = "Contact"
    weight = 3
    
# Main menu

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontello.com

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "gplus"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "pinterest-circled"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "instagram"
    weight = 5
       

[Params.widgets]
    author = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
        
        
[params.authors]
[params.authors.hash]
    name = "Hash Borgir"

    bio = "Hash is a Software Developer and generally a tech geek and computer nerd. He also consumes massive quantities of Cannabis and takes extremely deep journeys inwardly, meditates, explores the Universe within."

    location = "Colorado, USA"
    email = ""
    twitter=  "HashBorgir"
    image = "/images/authors/Hash_Borgir/user.jpg"
    instagram = "hashborgir"

#[params.authors.guest]
#    name = "Guest Writer"
#
#   bio = "Guest author profile. No bio. "
#
#    location = "Colorado, USA"
#    email = ""
#    twitter=  ""
#    image = "/images/authors/Guest/gust.jpg"
#    instagram = ""
