---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - ''
- name: slug
  label: Slug
  type: text
  hidden: false
  default: apa-itu-vps
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: featured_image
  label: Featured image
  type: text
  hidden: false
  default: "/images/"
- name: authors
  label: Authors
  type: tag_list
  hidden: false
  default:
  - akhlis
